# Generated by Django 4.2.3 on 2023-08-05 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProdName', models.CharField(max_length=255)),
                ('BrandID', models.IntegerField()),
                ('CategoryID', models.IntegerField()),
                ('SupplierID', models.IntegerField()),
                ('cost', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
            options={
                'db_table': 'product',
            },
        ),
    ]
