# Generated by Django 4.2.3 on 2023-08-18 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='status',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
