# Generated by Django 4.2.3 on 2023-08-20 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_purchase_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='total',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
