# Generated by Django 4.2.3 on 2023-08-21 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_purchase_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='predict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProdID', models.IntegerField()),
                ('weekDay', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
            ],
            options={
                'db_table': 'predict',
            },
        ),
    ]
