# Generated by Django 4.2.3 on 2023-08-21 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_predict'),
    ]

    operations = [
        migrations.CreateModel(
            name='weekPredict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProdID', models.IntegerField()),
                ('quantity', models.IntegerField()),
            ],
            options={
                'db_table': 'weekPredict',
            },
        ),
    ]
