# Generated by Django 4.2.3 on 2023-08-08 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CustName', models.CharField(max_length=255)),
                ('birthday', models.DateField(auto_now_add=True)),
                ('phone', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'customer',
            },
        ),
        migrations.CreateModel(
            name='sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProdName', models.CharField(max_length=255)),
                ('ProdID', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('CustName', models.CharField(max_length=255)),
                ('CustID', models.IntegerField()),
                ('saleDate', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'sale',
            },
        ),
    ]
