# Generated by Django 4.2.3 on 2023-08-20 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0003_sale_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='CustID',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='CustName',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
