# Generated by Django 4.2.3 on 2023-08-22 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0004_alter_sale_custid_alter_sale_custname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='status',
        ),
    ]
